# Generated by Django 5.1 on 2024-09-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='curso',
        ),
        migrations.AddField(
            model_name='professor',
            name='cursos',
            field=models.ManyToManyField(related_name='professores', to='sec_chatbot.curso'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(related_name='professores', to='sec_chatbot.turma'),
        ),
    ]
