# Generated by Django 5.1 on 2024-09-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_chatbot', '0002_remove_professor_curso_professor_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='materia_lecionada',
            field=models.ManyToManyField(related_name='professores', to='sec_chatbot.materia'),
        ),
    ]
